[package]
name = "ecommerce-client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.17"
async-stream = "0.3"
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.6"
